controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api:
    resource:
        path: ../src/ApiController/
        namespace: App\ApiController
    type: attribute
    prefix: '/api/'
    condition: "service('App\\\\Service\\\\AuthorizationTokenService').check(request)"