name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MONGODB_URL: mongodb://mongo:27017

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7.0.4
        ports:
          - 27017:27017
        healthcheck:
          test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
          interval: 10s
          timeout: 10s
          retries: 5
          start_period: 40s

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: php bin/phpunit
